name: Build and Test

on: [push]

env:
  registry: ghcr.io

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build Focal" ]
        include:
        
          - name: "Build Focal"
            release: focal
    
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Get Name
        run: echo "name=$(echo ${GITHUB_REF//\//_} | cut -c 6-)" >> $GITHUB_ENV

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_TOKEN }}
          
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: docker/${{ matrix.release }}
          file: docker/${{ matrix.release }}/Dockerfile
          push: true
          tags: ${{ env.registry }}/cianwilson/vankeken_wilson_peps_2023:${{ env.name }}-${{ matrix.release }}
          no-cache: true
          platforms: linux/amd64,linux/arm64

  testing:

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: build
    if: always()

    strategy:
      fail-fast: false
      matrix:
        name: [ "Tests" ]
        include:

          - name: "Tests Focal"
            release: focal
            command: "./scripts/run_tests"
            outputdir: "tests"
            outputtar: "tests.tar.gz"

    steps:

      - name: ${{ matrix.name }} Name
        run: echo "name=$(echo ${GITHUB_REF//\//_} | cut -c 6-)" >> $GITHUB_ENV

      - name: ${{ matrix.name }} Testing
        run: |
         chmod 777 .
         docker pull ${{ env.registry }}/cianwilson/vankeken_wilson_peps_2023:${{ env.name }}-${{ matrix.release }}
         docker run -v $PWD:/home/tfuser/shared -e HOST_UID=`id -u` -e HOST_GID=`id -g` --workdir /home/tfuser/vankeken_wilson_peps_2023 ${{ env.registry }}/cianwilson/vankeken_wilson_peps_2023:${{ env.name }}-${{ matrix.release }} "${{ matrix.command }} || ( tar --exclude=*.build -cvzf ${{ matrix.outputtar }} .; cp -v ${{ matrix.outputtar }} /home/tfuser/shared; ( exit 1 ) )"

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: ${{ matrix.outputtar }}
          name: failed_test_outputs


